### PR TITLE
Throw warning if DATABASE_URL isn't set

### PR DESCRIPTION
**Pull request by palfrey**
Fixes https://github.com/jazzband/dj-database-url/issues/114

Along the way, to make the test cleaner, it fixes all the explicit "set os.environ" calls with `mock.patch` work instead.

### CODE REVIEW

**Comment by mattseymour** [comment]
Whilst I get what this PR is trying to do I do not think adding in extra parameters is the correct way to do this. It seems like a messy API design.

We also need to be wary that a user might want the `default` to be None in which case you have changed the api.

I think this needs to be thought over before proceeding.

**Comment by palfrey** [comment]
> Whilst I get what this PR is trying to do I do not think adding in extra parameters is the correct way to do this. It seems like a messy API design.

Agreed, but I thought that was where consensus in https://github.com/jazzband/dj-database-url/issues/114 had gotten to, hence adding it. I can remove that bit if you want.
 
> We also need to be wary that a user might want the `default` to be None in which case you have changed the api.

If they do that, then it won't configure a database at all. I'd say that the working assumption for this library is "users always want a DB", and that warnings should flag if we're failing to do that. So, anything _other_ than None is a perfectly good value and should be fed to `parse`, but None should warn IMHO.

Thoughts?

**Comment by palfrey** [comment]
@ddelange @mattseymour I've updated this in line with the description now in https://github.com/jazzband/dj-database-url/issues/114#issuecomment-1406861561 which I think is the right middle ground here. Thoughts? Can I merge?

**Review by ddelange — APPROVED** [review]
super many thanks!

**Pull request merged**
