### PR TITLE
allow TEST settings to be passed into a db config

### LINKED ISSUE #102: How can we specify the name of the test database?
Django supports a custom name for the test database, how can we specify this somehow?

See https://docs.djangoproject.com/en/1.8/ref/settings/#test

### PR DESCRIPTION
**Pull request by Brodan**
currently DB configs do not allow for a 'TEST' configuration to be passed in, this PR will allow it. 

Fixes #102.

### CODE REVIEW

**Comment by Brodan** [comment]
@sigmavirus24 can you or someone please take a look at this. thanks!

**Comment by sigmavirus24** [comment]
I no longer maintain this package

**Comment by Brodan** [comment]
Does anyone maintain it? If not I would be willing to take it over. Please let me know, @sigmavirus24.

**Comment by sigmavirus24** [comment]
I can't answer that or give you those rights, please stop mentioning me on this

**Comment by Brodan** [comment]
@kenneth-reitz Can you assist?

**Comment by Brodan** [comment]
Bump, kinda sucks that no one will look at this. I'm willing to take over the repo, still seems relevant and like a lot of people use it.

**Comment by MattOates** [comment]
Some feedback on this PR your` test={}` is `config.update` is at the top level of the DB config. It would be cleaner and more specific if your code did `config.update({'TEST': test})` to make sure it's only altering the TEST settings. Otherwise it's not really anything to do with test, but a generic dict you can patch anything with.

**Comment by Brodan** [comment]
Hey @jacobian! I noticed this repo just changed owners, think you can take a look at this soon?

**Comment by jacobian** [comment]
@Brodan I will try, no promises though. I've taken this over as an interim thing (see #120) and am not yet totally sure what my level of commitment I'm up for.

---

On a more meta note: if this issue is indicative of how you engage with open source, I'd suggest you think carefully about your approach. I know it can be super-frustrating having an issue you care about linger! But you have to remember that the vast majority of open source is maintained by people doing work in their spare time. Vanishingly few of us are paid for our time, and most of us have a ton of other commitments. We work on this stuff when we can, but it's often not a lot of time.

Given that context, I hope you'll see why pinging people to take a look at your work isn't particularly effective. It adds to an already stressful situation, and can lead to burnout. It's a counter-productive spiral: added stress means that working on the project doesn't seem like much fun, which adds more stress, and down we go. Paradoxically, the more you ask, the less folks want to help.

I know your intention here is good: clearly you're not intending to be a pest! But I hope you'll think a bit about how the repeated pings look from a maintainer's POV.

--- 

Again, I'll see if I can get around to this shortly, but I can't make any promises, sorry.

**Comment by Brodan** [comment]
Thank you for your feedback @jacobian. While I feel that my engagement in this thread was respectful and not out of the ordinary, I understand your points and will try to be more mindful in the future. 

There's no rush to getting this merged of course, but it's nice to know that _someone_ will eventually look at this, as it's something that can benefit more than just myself based on what I've seen.

**Comment by jacobian** [comment]
@Brodan thanks for understanding.

OK, I've taken a look, and this mostly looks good. I've got two small changes that I'd like to request before merging:

1. The documentation (README) needs to be updated explaining that this is possible.
2. Very minor, but I think the argument should be `test_name` rather than just `test`. At first I wasn't sure if I should just pass the database name, or the whole `test` dictionary (e.g. `{"test": "default"}`); renaming it to `test_name` (or even `test_database_name`?) makes this more clear.

Thanks!

**Comment by Brodan** [comment]
@jacobian Thank you for the quick review!

`test` is actually intended to be a dictionary, since more than just `NAME` can be configured. I updated the variable name to `test_options`. Hopefully that's a little better. 

I also added a note about this new option in the README under 'Usage'. Let me know your thoughts. I can make changes again if necessary.

**Comment by mattseymour** [comment]
I think naming it `test_options` is a good shout. This change looks good to me.

**Comment by Brodan** [comment]
bump!

**Comment by Brodan** [comment]
Bumping this again. Would love if it could be looked at as I could use this feature at work and others have also expressed interest! It's quite a small PR

**Comment by mattseymour** [comment]
This PR code seems to cover all the points raised above and in the various issues. I think its probably at a good point to merge into the main branch if no one has any objections.

**Comment by Brodan** [comment]
Bump, is there anything I can do to help get this merged? It's over a year old. I'd rather not have to fork and package this on my own. This would solve an enormous pain-point I'm having at work.

**Comment by Brodan** [comment]
Bumping again. @jacobian Is there anything blocking this from being merged? It's been open for nearly two years...

**Comment by Brodan** [comment]
@jacobian bumping again

**Comment by Brodan** [comment]
@jazzband now that this has been transferred over can anyone finally take a look at this and get it over the finish line?

**Comment by palfrey** [comment]
> @jazzband now that this has been transferred over can anyone finally take a look at this and get it over the finish line?

I've just joined jazzband, mostly to help with this project a bit :) If you can fix the conflicts, I'm happy to get this merged in.

**Comment by Brodan** [comment]
@palfrey Done! Thanks so much for actually taking a look. Lemme know if my update is sufficient

**Comment by mattseymour** [comment]
Need to make a small change to this there is the potential for a bug to crop up.

**Comment by Brodan** [comment]
> Need to make a small change to this there is the potential for a bug to crop up.

Can you elaborate? I'd be happy to open a follow-up PR if this you can explain what the issue is.

**Pull request merged**
