### PR TITLE
fix: parse options with numerical values as int

### LINKED ISSUE #222: Option value `connect_timeout` returned as string instead of int
Version: 1.3.0 and 2.0.0

Example:
```python
import dj_database_url

print(dj_database_url.parse("mysql://user:pw@127.0.0.1:15036/db?connect_timout=3"))
```

Returns:
```python
{'NAME': 'db', 'USER': 'user', 'PASSWORD': 'pw', 'HOST': '127.0.0.1', 'PORT': 15036, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'ENGINE': 'django.db.backends.mysql',
'OPTIONS': {'connect_timout': '3'}}
```

Expected:
```python
{'NAME': 'db', 'USER': 'user', 'PASSWORD': 'pw', 'HOST': '127.0.0.1', 'PORT': 15036, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'ENGINE': 'django.db.backends.mysql',
'OPTIONS': {'connect_timout': 3}}
```

Error:
```
  ...
  File ".venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File ".venv/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File ".venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
TypeError: an integer is required (got type str)
```

Suggested fix:
```python
try:
   value = int(value)
except (TypeError, ValueError):
   value = value
```

### PR DESCRIPTION
**Pull request by estahn**
fixes #222

### CODE REVIEW

**Comment by estahn** [comment]
@mattseymour 👋🏼 Can I get you to have a look at this?

**Comment by estahn** [comment]
If this can not be generalised we could have an index of options that require conversion to `int`.

**Comment by woodsae** [comment]
Amazing, I've been waiting for this fix!

**Comment by mattseymour** [comment]
Nice one, I am going to start building a v2.1.0 release now.

**Pull request merged**
